<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Go Home' => '',
    'About' => '',
    'Available stock' => '',
    'Best route from your location' => '',
    'Cancel' => '',
    'Create' => '',
    'Create Order' => '',
    'Day' => '',
    'Delivered' => '',
    'Deliveries' => '',
    'Delivery Items' => '',
    'Delivery day' => '',
    'Done' => '',
    'Go back' => '',
    'Home' => '',
    'Hours' => '',
    'If you forgot your password you can' => '',
    'Image' => '',
    'It looks like the order doesnt exist' => '',
    'It\'s nice see you again' => '',
    'It\'s nice see you!' => '',
    'Login' => '',
    'Name' => '',
    'New Order' => '',
    'New delivery stock' => '',
    'New order' => '',
    'Next week' => '',
    'Oh, oh! No shops are available' => '',
    'Please' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Please fill out the following fields to login' => '',
    'Please go back' => '',
    'Select Shop' => '',
    'Shop' => '',
    'Stock' => '',
    'Stock for order' => '',
    'Take new orders!' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'Theres no data to show' => '',
    'This week' => '',
    'Today' => '',
    'Tomorrow' => '',
    'Welcome back' => '',
    'Welcome back .. guest?' => '',
    'Your best route for today' => '',
    'login' => '',
    'or' => '',
    'password' => '',
    'rememberMe' => '',
    'reset it' => '',
    'signup' => '',
    'username' => '',
];
