<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Go Home' => '',
    'Add products' => '',
    'Add products to ' => '',
    'Adress' => '',
    'Are you sure you want to delete this item?' => '',
    'Categories' => '',
    'Category' => '',
    'Change Picture' => '',
    'Choose from the list to add a product' => '',
    'Choose from the list to remove a product' => '',
    'Click to add' => '',
    'Click to remove' => '',
    'Create' => '',
    'Create Ruta' => '',
    'Create categories' => '',
    'Create product' => '',
    'Date' => '',
    'Day to control stock' => '',
    'Delete' => '',
    'Employee' => '',
    'Friday' => '',
    'I forgot my password' => '',
    'ID' => '',
    'Image' => '',
    'Latitude' => '',
    'Location' => '',
    'Longitude' => '',
    'Monday' => '',
    'Name' => '',
    'Online' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Priority' => '',
    'Product picture' => '',
    'Products' => '',
    'Products in store' => '',
    'Register a new membership' => '',
    'Register store' => '',
    'Relevated' => '',
    'Request' => '',
    'Route' => '',
    'Routes' => '',
    'Rutas' => '',
    'Saturday' => '',
    'Search...' => '',
    'Shop' => '',
    'Sign in' => '',
    'Sign out' => '',
    'Stock' => '',
    'Store' => '',
    'Stores' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'Thursday' => '',
    'Tuesday' => '',
    'Unassign products' => '',
    'Update' => '',
    'Update picture of {modelClass}: ' => '',
    'Update {modelClass}: ' => '',
    'Users' => '',
    'Wednesday' => '',
    'product' => '',
    'shop' => '',
];
