<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Already registered? Sign in!' => '',
    'Continue' => '',
    'Don\'t have an account? Sign up!' => '',
    'If you already registered, sign in and connect this account on settings page' => '',
    'In order to finish your registration, we need you to enter following fields' => '',
    'Request new confirmation message' => '',
    'Sign in' => '',
    'Sign up' => '',
    'You don\'t have admin permission' => '',
    'Your account has been created' => '',
];
