<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Las asignaciones se han actualizado',
    'Auth item with such name already exists' => 'Elemento de autenticación con ese nombre ya existe',
    'Children' => 'Hijo',
    'Class "{0}" does not exist' => 'Clase "{0}" no existe',
    'Create' => 'Crear',
    'Create new permission' => 'Crear nuevo permiso',
    'Create new role' => 'Crear nuevo rol',
    'Description' => 'Descripcion',
    'Invalid value' => 'Valor invalido',
    'Item has been created' => 'Item ha sido creado',
    'Item has been updated' => 'Item ha sido actualizado',
    'Items' => 'Items',
    'Name' => 'Nombre',
    'New permission' => 'Nuevo permiso',
    'New role' => 'Nuevo rol',
    'New user' => 'Nuevo usuario',
    'Permissions' => 'Permisos',
    'Roles' => 'Roles',
    'Rule' => 'Regla',
    'Rule class can not be instantiated' => 'Clase de regla no puede ser instanciada',
    'Rule class must extend "yii
bacRule"' => 'Clase de regla debe extender "yii bacRule"',
    'Rule name' => 'Nombre de regla',
    'Save' => 'Guardar',
    'There is neither role nor permission with name "{0}"' => 'No hay role o permiso con el nombre "{0}"',
    'Update assignments' => 'Actualizar asignaciones',
    'Update permission' => 'Actualizar permisos',
    'Update role' => 'Actualizar role',
    'Users' => 'Usuarios',
];
